seed: 42

data:
  path_to_csv: "C:\\Users\\julie\\Documents\\Data_Projet\\Data_v2.csv"
  base_image_dir: "C:\\Users\\julie\\Documents\\Data_Projet\\mission_herbonaute_2000"
  segmented_image_dir: "C:\\Users\\julie\\Documents\\Data_Projet\\mission_herbonaute_2000_seg_black"
  image_ext: ".jpg"

split:
  train_test: 0.80
  train_val: 0.80

model:
  epochs: 10
  batch_size: 8
  lr: 0.0001
  weight_decay: 0.05
  num_workers: 2
  img_size: 224
  amp: true

output:
  dir: "outputs/part_1"
  save_best_on: "f1"

training:
  batch_size: 32
  epochs: 20
  lr: 0.001